add_newline = false
format = """$directory$character"""
palette = "alabaster"
right_format = """$all"""
command_timeout = 1000

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[docker_context]
disabled = true

[palettes.alabaster]
black = "#000000"
red = "#D2322D"
green = "#6ABF40"
yellow = "#CD974B"
blue = "#217EBC"
purple = "#9B3596"
cyan = "#178F79"
white = "#CECECE"
bright-black = "#333333"
bright-red = "#C33C33"
bright-green = "#95CB82"
bright-yellow = "#DFDF8E"
bright-blue = "#71AED7"
bright-purple = "#CC8BC9"
bright-cyan = "#47BEA9"
bright-white = "#FFFFFF"
