require('mini.ai').setup()
require('mini.surround').setup()
require('mini.operators').setup()
require('mini.pairs').setup()
require('mini.bracketed').setup()
require('mini.files').setup()
require('mini.starter').setup()
require('mini.tabline').setup()
require('mini.statusline').setup()
require('mini.trailspace').setup()
require('mini.clue').setup()
require('mini.animate').setup({ scroll = { enable = false } })
